name = "BirthDeathShiftSim"
uuid = "ad479ac2-0729-4de6-bd45-24a4975c5af2"
authors = ["Bjorn Tore Kopperud <kopperud@protonmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
BirthDeathShiftSimMakieExt = ["Makie"]

[compat]
ProgressMeter = "1.10.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
